name: FactionMasterAdminTools
author: ShockedPlot7560
version: 2.0.1
api: 4.0.0
main: ShockedPlot7560\FactionMasterAdminTools\FactionMasterAdminTools
src-namespace-prefix: ShockedPlot7560\FactionMasterAdminTools
depend: [FactionMaster]
description: "Extension which add an administration gestion"
permissions:
  factionmaster.admin.faction.delete:
    description: "Allow the player to delete any faction via the admin tool"
    default: "op"
  factionmaster.admin.invitation.delete:
    description: "Allow the player to delete any invitation via the admin tool"
    default: "op"
  factionmaster.admin.home.delete:
    description: "Allow the player to delete any faction's home via the admin tool"
    default: "op"
  factionmaster.admin.faction.update:
    description: "Allow the player to give a reward to any faction via the admin tool"
    default: "op"
  factionmaster.admin.claim.delete:
    description: "Allow the player to delete any claim via the admin tool"
    default: "op"
  factionmaster.admin.tp.home:
    description: "Allow the player tp to any faction's home"
    default: "op"
  factionmaster.admin.tp.claim:
    description: "Allow the player tp to any faction's claim"
    default: "op"