name: FactionMasterAdminTools
author: ShockedPlot7560
version: 1.1.0-alpha
api: 3.17.7
main: ShockedPlot7560\FactionMasterAdminTools\Main
softdepend: [FactionMaster]
description: "Extension which add an administration gestion"
permissions:
  factionmaster.admin.faction.delete:
    description: "Allow the player to delete any faction via the admin tool"
    default: "op"
  factionmaster.admin.invitation.delete:
    description: "Allow the player to delete any invitation via the admin tool"
    default: "op"
  factionmaster.admin.home.delete:
    description: "Allow the player to delete any faction's home via the admin tool"
    default: "op"
  factionmaster.admin.faction.update:
    description: "Allow the player to give a reward to any faction via the admin tool"
    default: "op"
  factionmaster.admin.claim.delete:
    description: "Allow the player to delete any claim via the admin tool"
    default: "op"
  factionmaster.admin.tp.home:
    description: "Allow the player tp to any faction's home"
    default: "op"
  factionmaster.admin.tp.claim:
    description: "Allow the player tp to any faction's claim"
    default: "op"